################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
user/testbin/userthreads \
user/testbin/triplesort \
user/testbin/triplesort/build \
user/testbin/triplemat \
user/testbin/triplemat/build \
user/testbin/triplehuge \
user/testbin/triplehuge/build \
user/testbin/tictac \
user/testbin/tictac/build \
user/testbin/tail \
user/testbin/tail/build \
user/testbin/sty \
user/testbin/sty/build \
user/testbin/sort \
user/testbin/sort/build \
user/testbin/sink \
user/testbin/sink/build \
user/testbin/rmtest \
user/testbin/rmtest/build \
user/testbin/rmdirtest \
user/testbin/rmdirtest/build \
user/testbin/randcall \
user/testbin/randcall/build \
user/testbin/psort \
user/testbin/psort/build \
user/testbin/parallelvm \
user/testbin/parallelvm/build \
user/testbin/palin \
user/testbin/palin/build \
user/testbin/matmult \
user/testbin/matmult/build \
user/testbin/malloctest \
user/testbin/malloctest/build \
user/testbin/kitchen \
user/testbin/kitchen/build \
user/testbin/huge \
user/testbin/huge/build \
user/testbin/hog \
user/testbin/hog/build \
user/testbin/hash \
user/testbin/hash/build \
user/testbin/guzzle \
user/testbin/guzzle/build \
user/testbin/forktest \
user/testbin/forktest/build \
user/testbin/forkbomb \
user/testbin/forkbomb/build \
user/testbin/filetest \
user/testbin/filetest/build \
user/testbin/fileonlytest \
user/testbin/fileonlytest/build \
user/testbin/faulter \
user/testbin/faulter/build \
user/testbin/farm \
user/testbin/farm/build \
user/testbin/f_test \
user/testbin/f_test/build \
user/testbin/dirtest \
user/testbin/dirtest/build \
user/testbin/dirseek \
user/testbin/dirseek/build \
user/testbin/dirconc \
user/testbin/dirconc/build \
user/testbin/ctest \
user/testbin/ctest/build \
user/testbin/crash \
user/testbin/crash/build \
user/testbin/conman \
user/testbin/conman/build \
user/testbin/bigfile/build \
user/testbin/bigfile \
user/testbin/badcall \
user/testbin/badcall/build \
user/testbin/argtest/build \
user/testbin/argtest \
user/testbin/add/build \
user/testbin/add \
user/sbin/sfsck \
user/sbin/sfsck/build \
user/sbin/reboot \
user/sbin/reboot/build \
user/sbin/poweroff \
user/sbin/poweroff/build \
user/sbin/mksfs \
user/sbin/mksfs/build \
user/sbin/halt \
user/sbin/halt/build \
user/sbin/dumpsfs \
user/sbin/dumpsfs/build \
user/lib/libc/unix \
user/lib/libc/time \
user/lib/libc/string \
user/lib/libc/stdlib \
user/lib/libc/stdio \
user/lib/libc/build \
user/lib/libc/arch/mips \
user/lib/hostcompat \
user/lib/crt0/mips \
user/lib/crt0/build \
user/build/testbin/triplesort \
user/build/testbin/triplemat \
user/build/testbin/triplehuge \
user/build/testbin/tictac \
user/build/testbin/tail \
user/build/testbin/sty \
user/build/testbin/sort \
user/build/testbin/sink \
user/build/testbin/rmtest \
user/build/testbin/rmdirtest \
user/build/testbin/randcall \
user/build/testbin/psort \
user/build/testbin/parallelvm \
user/build/testbin/palin \
user/build/testbin/matmult \
user/build/testbin/malloctest \
user/build/testbin/kitchen \
user/build/testbin/huge \
user/build/testbin/hog \
user/build/testbin/hash \
user/build/testbin/guzzle \
user/build/testbin/forktest \
user/build/testbin/forkbomb \
user/build/testbin/filetest \
user/build/testbin/faulter \
user/build/testbin/farm \
user/build/testbin/f_test \
user/build/testbin/dirtest \
user/build/testbin/dirseek \
user/build/testbin/dirconc \
user/build/testbin/ctest \
user/build/testbin/crash \
user/build/testbin/conman \
user/build/testbin/bigfile \
user/build/testbin/badcall \
user/build/testbin/argtest \
user/build/testbin/add \
user/build/sbin/sfsck \
user/build/sbin/reboot \
user/build/sbin/poweroff \
user/build/sbin/mksfs \
user/build/sbin/halt \
user/build/sbin/dumpsfs \
user/build/lib/libc \
user/build/lib/crt0 \
user/build/bin/true \
user/build/bin/sync \
user/build/bin/sh \
user/build/bin/rmdir \
user/build/bin/rm \
user/build/bin/pwd \
user/build/bin/mv \
user/build/bin/mkdir \
user/build/bin/ls \
user/build/bin/ln \
user/build/bin/false \
user/build/bin/cp \
user/build/bin/cat \
user/bin/true \
user/bin/true/build \
user/bin/sync \
user/bin/sync/build \
user/bin/sh \
user/bin/sh/build \
user/bin/rmdir \
user/bin/rmdir/build \
user/bin/rm \
user/bin/rm/build \
user/bin/pwd \
user/bin/pwd/build \
user/bin/mv \
user/bin/mv/build \
user/bin/mkdir \
user/bin/mkdir/build \
user/bin/ls \
user/bin/ls/build \
user/bin/ln \
user/bin/ln/build \
user/bin/false \
user/bin/false/build \
user/bin/cp \
user/bin/cp/build \
user/bin/cat \
user/bin/cat/build \
kern/vm \
kern/vfs \
kern/thread \
kern/test \
kern/syscall \
kern/synchprobs \
kern/startup \
kern/lib \
kern/fs/sfs \
kern/dev/lamebus \
kern/dev/generic \
kern/compile/ASST3 \
kern/compile/ASST2-OPT \
kern/compile/ASST2 \
kern/compile/ASST1 \
kern/arch/sys161/startup \
kern/arch/sys161/dev \
kern/arch/mips/vm \
kern/arch/mips/thread \
kern/arch/mips/syscall \
kern/arch/mips/locore \
common/libc/string \
common/libc/stdlib \
common/libc/printf \
common/libc/arch/mips \
common/gcc-millicode \
build/user/testbin/triplesort \
build/user/testbin/triplemat \
build/user/testbin/triplehuge \
build/user/testbin/tictac \
build/user/testbin/tail \
build/user/testbin/sty \
build/user/testbin/sort \
build/user/testbin/sink \
build/user/testbin/rmtest \
build/user/testbin/rmdirtest \
build/user/testbin/randcall \
build/user/testbin/psort \
build/user/testbin/parallelvm \
build/user/testbin/palin \
build/user/testbin/matmult \
build/user/testbin/malloctest \
build/user/testbin/kitchen \
build/user/testbin/huge \
build/user/testbin/hog \
build/user/testbin/hash \
build/user/testbin/guzzle \
build/user/testbin/forktest \
build/user/testbin/forkbomb \
build/user/testbin/filetest \
build/user/testbin/fileonlytest \
build/user/testbin/faulter \
build/user/testbin/farm \
build/user/testbin/f_test \
build/user/testbin/dirtest \
build/user/testbin/dirseek \
build/user/testbin/dirconc \
build/user/testbin/ctest \
build/user/testbin/crash \
build/user/testbin/conman \
build/user/testbin/bigfile \
build/user/testbin/badcall \
build/user/testbin/argtest \
build/user/testbin/add \
build/user/sbin/sfsck \
build/user/sbin/reboot \
build/user/sbin/poweroff \
build/user/sbin/mksfs \
build/user/sbin/halt \
build/user/sbin/dumpsfs \
build/user/lib/libc \
build/user/lib/crt0 \
build/user/bin/true \
build/user/bin/sync \
build/user/bin/sh \
build/user/bin/rmdir \
build/user/bin/rm \
build/user/bin/pwd \
build/user/bin/mv \
build/user/bin/mkdir \
build/user/bin/ls \
build/user/bin/ln \
build/user/bin/false \
build/user/bin/cp \
build/user/bin/cat \
build/install/lib \

